/**
 * Telegram Bot Configuration
 * Generated by Configuration Helper on 10.06.2025, 12:58:01
 */

const TELEGRAM_CONFIG = {
  // Bot Token from @BotFather
  BOT_TOKEN: '8363289249:AAFu2CNjZCWJlDpI9Fo2NisuPrxgDOgLW8c',
  
  // Your Chat ID
  CHAT_ID: '-1003835459239',
  
  // Python Chat Server URL - Replit Server (TEMPORARY DEV URL)
  SERVER_URL: 'https://c63f9f1a-f9bd-4cfc-8d82-3fc0315d4d9c-00-16at38u7iobmy.spock.replit.dev',
  
  // Telegram API URL
  API_URL: 'https://api.telegram.org/bot',
  
  // Message formatting options
  MESSAGE_OPTIONS: {
    parse_mode: 'HTML',
    disable_web_page_preview: true
  },
  
  // Emojis for different notification types
  EMOJIS: {
    new_order: '🛒',
    customer: '👤',
    items: '📦',
    price: '💰',
    message: '💬',
    time: '⏰',
    success: '✅',
    error: '❌'
  }
};

// Export configuration
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TELEGRAM_CONFIG;
} else {
  window.TELEGRAM_CONFIG = TELEGRAM_CONFIG;
}